# These limits are used by MoveIt and augment/override the definitions in ur_description.
#
# While the robot does not inherently have any limits on joint accelerations (only on torques),
# MoveIt needs them for time parametrization. They were chosen conservatively to work in most use
# cases. For specific applications, higher values might lead to better execution performance.

joint_limits:
  la_shoulder_pan_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  la_shoulder_lift_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  la_elbow_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  la_wrist_1_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  la_wrist_2_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  la_wrist_3_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  ra_shoulder_pan_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  ra_shoulder_lift_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  ra_elbow_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  ra_wrist_1_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  ra_wrist_2_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  ra_wrist_3_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0