controller_manager:
  ros__parameters:
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
  
    la_io_and_status_controller:
      type: ur_controllers/GPIOController

    la_speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster

    la_force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    la_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    la_scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController

    la_forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    la_forward_position_controller:
      type: position_controllers/JointGroupPositionController
      
    ra_io_and_status_controller:
      type: ur_controllers/GPIOController

    ra_speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster

    ra_force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    ra_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    ra_scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController

    ra_forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    ra_forward_position_controller:
      type: position_controllers/JointGroupPositionController


la_speed_scaling_state_broadcaster:
  ros__parameters:
    state_publish_rate: 100.0
    tf_prefix: "la_"

la_io_and_status_controller:
  ros__parameters:
    tf_prefix: "la_"

la_force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: la_tcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: la_tool0
    topic_name: ft_data


la_joint_trajectory_controller:
  ros__parameters:
    joints:
      - la_shoulder_pan_joint
      - la_shoulder_lift_joint
      - la_elbow_joint
      - la_wrist_1_joint
      - la_wrist_2_joint
      - la_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      la_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      la_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      la_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      la_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      la_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      la_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }


la_scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - la_shoulder_pan_joint
      - la_shoulder_lift_joint
      - la_elbow_joint
      - la_wrist_1_joint
      - la_wrist_2_joint
      - la_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      la_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      la_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      la_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      la_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      la_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      la_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
    speed_scaling_interface_name: la_speed_scaling/speed_scaling_factor

la_forward_velocity_controller:
  ros__parameters:
    joints:
      - la_shoulder_pan_joint
      - la_shoulder_lift_joint
      - la_elbow_joint
      - la_wrist_1_joint
      - la_wrist_2_joint
      - la_wrist_3_joint
    interface_name: velocity

la_forward_position_controller:
  ros__parameters:
    joints:
      - la_shoulder_pan_joint
      - la_shoulder_lift_joint
      - la_elbow_joint
      - la_wrist_1_joint
      - la_wrist_2_joint
      - la_wrist_3_joint

ra_speed_scaling_state_broadcaster:
  ros__parameters:
    state_publish_rate: 100.0
    tf_prefix: "ra_"

ra_io_and_status_controller:
  ros__parameters:
    tf_prefix: "ra_"

ra_force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: ra_tcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: ra_tool0
    topic_name: ft_data


ra_joint_trajectory_controller:
  ros__parameters:
    joints:
      - ra_shoulder_pan_joint
      - ra_shoulder_lift_joint
      - ra_elbow_joint
      - ra_wrist_1_joint
      - ra_wrist_2_joint
      - ra_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      ra_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      ra_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      ra_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      ra_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      ra_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      ra_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }


ra_scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - ra_shoulder_pan_joint
      - ra_shoulder_lift_joint
      - ra_elbow_joint
      - ra_wrist_1_joint
      - ra_wrist_2_joint
      - ra_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      ra_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      ra_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      ra_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      ra_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      ra_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      ra_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
    speed_scaling_interface_name: ra_speed_scaling/speed_scaling_factor

ra_forward_velocity_controller:
  ros__parameters:
    joints:
      - ra_shoulder_pan_joint
      - ra_shoulder_lift_joint
      - ra_elbow_joint
      - ra_wrist_1_joint
      - ra_wrist_2_joint
      - ra_wrist_3_joint
    interface_name: velocity

ra_forward_position_controller:
  ros__parameters:
    joints:
      - ra_shoulder_pan_joint
      - ra_shoulder_lift_joint
      - ra_elbow_joint
      - ra_wrist_1_joint
      - ra_wrist_2_joint
      - ra_wrist_3_joint